name: memogenerator
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  rxdart: ^0.27.2
  provider: ^6.0.1
  google_fonts: ^2.1.0
  uuid: ^3.0.5
  stream_transform: ^2.0.0
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+4
  path_provider: ^2.0.6
  screenshot: ^1.2.3
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  build_runner: ^2.1.5

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/